# Generated by Django 5.0.3 on 2025-04-30 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='products_discussed',
        ),
    ]
